services:
  postgresql:
    container_name: password-manager-db
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_manager_prod
      POSTGRES_PASSWORD: password_manager_prod
      POSTGRES_DB: password_manager_db
    volumes:
      - pgdata:/bitnami/postgresql
    restart: always

volumes:
  pgdata:
