services:
  postgresql:
    container_name: password-manager-db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: password_manager_db
    volumes:
      - pgdata:/bitnami/postgresql
    restart: always

volumes:
  pgdata:
